# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: use npm@7
      run: npm i -g npm@7
    - name: Environment info
      run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
    - name: Install dependencies for workspaces
      run: npm install
    - name: Build with retry
      uses: nick-invision/retry@v2.4.0
      with:
        timeout_minutes: 1
        max_attempts: 3
        retry_on: error
        command: npm run build --if-present
    - run: npm test --if-present
